pull_request_title: "fix: new Crowdin updates"
commit_message: "fix(locale): new translations %original_file_name% from Crowdin"
files:
  - source: /language/en-GB/*.ini
    translation: /site/languages/%locale%/%original_file_name%
  - source: /administrator/language/en-GB/*.ini
    translation: /administrator/languages/%locale%/%original_file_name%

