CREATE TABLE IF NOT EXISTS `#__plugnmeet_room` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` VARCHAR(255) NOT NULL DEFAULT '',
	`attendee_pass` VARCHAR(64) NOT NULL DEFAULT '',
	`catid` INT(11) NOT NULL DEFAULT 0,
	`description` TEXT NOT NULL,
	`max_participants` INT(10) NOT NULL DEFAULT 0,
	`moderator_pass` VARCHAR(64) NOT NULL DEFAULT '',
	`room_id` VARCHAR(64) NOT NULL DEFAULT '',
	`room_metadata` TEXT NOT NULL,
	`room_title` VARCHAR(255) NOT NULL DEFAULT '',
	`welcome_message` TEXT NOT NULL,
	`params` text NULL,
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL,
	`metadesc` TEXT NOT NULL,
	`metadata` TEXT NOT NULL,
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_room_id` (`room_id`),
	KEY `idx_room_title` (`room_title`),
	KEY `idx_catid` (`catid`),
	KEY `idx_alias` (`alias`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;


