name: Generate component and upload as release asset
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
      - name: Build component
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p build
          
          rsync -ar --exclude="plugnmeet.xml" ./administrator/components/com_plugnmeet/* ./build/administrator/
          rsync -a ./administrator/components/com_plugnmeet/plugnmeet.xml ./build/
          rsync -a script.php ./build/
          
          rsync -ar  ./administrator/language/* ./build/administrator/languages/
          rsync -ar  ./administrator/language/* ./build/administrator/languages/
          
          rsync -ar ./components/com_plugnmeet/* ./build/site/
          rsync -ar  ./language/* ./build/site/languages/
          
          cd ./build
          zip -r com_plugnmeet.zip *
          gh release upload ${{ steps.release.outputs.tag_name }} com_plugnmeet.zip
